### PR TITLE
Data polling: fix bugs, refactor

### LINKED ISSUE #2: Home app shows old value after change
**Describe The Bug:**
After changing the target temperature or other values via the Home app, it may show the old value for a few seconds before updating to the expected value.

**To Reproduce:**
Go to the thermostat in the Home app. Change the target temperature. Note that it may show the new temperature momentarily but then reverts to the old temp for several seconds before finally changing to the new temperature for good.

**Expected behavior:**
Always show the new value after changing it.

### PR DESCRIPTION
**Pull request by FabianFrank**
1. Accessories no longer poll every 2 seconds but subscribe to updates
   with a callback (more predictable/simpler)
2. Updates are only announced to subscribers and subscribers only push
   updates into HomeKit after a full fetch from the accessory (prevents
   stale data from local cache from being pushed back into Homekit)
3. Data fetching from the accessory is delayed by 15s after making
   changes to prevent reading stale data from the accessory/Daikin.
4. Data is refreshed every 180s in the background and updated on demand
   when a user interacts with a HomeKit controler.

Fixes #2.

### CODE REVIEW

File: src/daikinapi.ts [hunk 1]
```diff
@@ -29,12 +30,29 @@ export declare const enum TargetHeatingCoolingState {
...
 export type LogMessage = (level: LoggerLevel, message: string, ...parameters: any[]) => void
 
+export type DataChanged = () => void
+
+// After sending an update to the Daikin API it will return old data for up to 15 seconds, so we
+// delay fetching data after an update by this amount. https://daikinone.com/openapi/documentation/
+export const DAIKIN_DEVICE_WRITE_DELAY_MS = 15*1000;
+
+// User is not interacting with a HomeKit controller - background updates for automations
+export const DAIKIN_DEVICE_BACKGROUND_REFRESH_MS = 180*1000;
```
Comment (FabianFrank) [inline src/daikinapi.ts:40]: This value right now replaces the `refreshInterval` config. We could make it configurable, but 3 minutes is the value Daikin calls out on https://daikinone.com/openapi/documentation/ so hopefully a value that won't ever raise any flags on their end.

File: src/daikinapi.ts [hunk 2]
```diff
@@ -29,12 +30,29 @@ export declare const enum TargetHeatingCoolingState {
...
+
+// User is interacting with a HomeKit controller - latest data needed
+export const DAIKIN_DEVICE_FOREGROUND_REFRESH_MS = 10*1000;
```
Comment (FabianFrank) [inline src/daikinapi.ts:43]: Since from all we can see the Daikin iOS app polls this API once every 10 seconds I found it to be a reasonable maximum frequency for when a user is viewing/using the data, i.e. we are at least not worse.

File: src/daikinapi.ts (hunk 1 above)
Comment (jeffschubert) [reply src/daikinapi.ts:40]: I'm good removing the refreshInterval.

**Review by jeffschubert — APPROVED** [review]

**Comment by jeffschubert** [comment]
I merged this into master, but I think other changes I made broke the link with this PR in some way. (I'm not completely familiar with all the ins and outs of git either.)
With these changes and your other improvements, I'm thinking of bumping the version up to 2.0. These are all significant enough to warrant that in my mind.

**Comment by FabianFrank** [comment]
@jeffschubert I think it's because I also pushed some more fixes while you were working on it. Either way I've merged `master` back into this branch so it can be merged again (much less changes now), which I think is what we have to do to make sure we get the last few fixes as well.

**Comment by jeffschubert** [comment]
Thanks, I think I've got it all squared away now. With the holidays, I'm not sure when I'll push a release, but I'd like to before the new year. If you find anything else, let me know.

**Comment by FabianFrank** [comment]
Awesome, thanks! Also once you push the release if you are interested I think the plugin now fulfills the requirements for being a [verified plugin](https://github.com/homebridge/verified#requirements) and we could apply to get verified. I'm a bit curious if they have further feedback on the plugin and would be happy to improve it a bit more if needed.

**Comment by jeffschubert** [comment]
Getting it verified has been a goal of mine as well. I'll look into after the new year.
